# -*- coding: utf-8 -*-
"""Check Even Or Odd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXMGmsVzmV2PJMlOMaswublMuGEIRSxU
"""

#Task 4
def check_even_odd():
    while True:
        input_value = input("Enter a number (or type 'exit' to quit): ")

        if input_value.lower() == 'exit':
            print("Goodbye! 👋")
            break

        try:
            number = int(input_value)

            if number % 2 == 0:
                print(f"🔢 {number} is an Even number.")
            else:
                print(f"🔢 {number} is an Odd number.")
        except ValueError:
            print("❌ Invalid input! Please enter a valid number.")

check_even_odd()