# -*- coding: utf-8 -*-
"""Password Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8i7L6vlf84lxj9xyssc-5KoWpN6DvFr
"""

# Task 6 🚀 Mission:
# Create a random password generator that generates strong passwords.
import random
import string

def generate_password(length, use_upper, use_lower, use_digits, use_symbols):
    if length < 8:
        print("Password length must be at least 8 characters!")
        return None

    char_pool = ""
    if use_upper:
        char_pool += string.ascii_uppercase
    if use_lower:
        char_pool += string.ascii_lowercase
    if use_digits:
        char_pool += string.digits
    if use_symbols:
        char_pool += string.punctuation

    if not char_pool:
        print("You must select at least one character type!")
        return None

    return ''.join(random.choice(char_pool) for _ in range(length))

# Ask user for inputs
num_passwords = int(input("How many passwords do you want to generate? "))
password_length = int(input("Enter password length (minimum 8): "))

use_upper = input("Include uppercase letters? (y/n): ").lower() == 'y'
use_lower = input("Include lowercase letters? (y/n): ").lower() == 'y'
use_digits = input("Include numbers? (y/n): ").lower() == 'y'
use_symbols = input("Include symbols? (y/n): ").lower() == 'y'

print("\nGenerated Passwords:")
for _ in range(num_passwords):
    password = generate_password(password_length, use_upper, use_lower, use_digits, use_symbols)
    if password:
        print(password)